namespace:
  name: spyder-apps

config:
  contents:
    OIDCIssuers:
      https://sts.windows.net/81fa766e-a349-4867-8bf4-ab35e250a08f/:
        IssuerURL: https://sts.windows.net/81fa766e-a349-4867-8bf4-ab35e250a08f/
        ClientID: https://management.azure.com/
        Type: username
        SubjectDomain: sts.windows.net
      # add aws equivalent here

server:
  #replicaCount: 2
  ingress:
    http:
      hosts:
        - path: /
          host: fulcio.dev.rdswf.net
      annotations:
        nginx.ingress.kubernetes.io/service-upstream: "true"
  #      cert-manager.io/cluster-issuer: letsencrypt
  args:
    ct_log_url: "http://ctlog.spyder-apps/sigstore"
    disable_ct_log: false
    # note: ct_log_url MUST be http, not https to work (at present at least)
  # logging:
  #   production: true

ctlog:
  enabled: true
  forceNamespace: "spyder-apps"
  namespace:
    name: spyder-apps

# resources??